#!/usr/bin/env sh
alias ka="killall" \
	mkd="mkdir -pv" \
	mpv="mpv --input-ipc-server=/tmp/mpvsoc$(date +%s)" \
	calcurse="calcurse -D ~/.config/calcurse" \
	magit="nvim -c MagitOnly" \
	p="sudo pacman" \
	SS="sudo systemctl" \
	f="$FILE" \
	g="git" \
	trem="transmission-remote" \
	e="$EDITOR" \
	v="$EDITOR -p" \
	x="sxiv -ft *" \
	sdn="sudo shutdown -h now" \
	gua="git remote | xargs -L1 git push --all" \
	#ls="ls -hNA --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff -y -i -w -B --color" \
	ccat="highlight --out-format=ansi" \
	yt="youtube-dl --add-metadata -i -o '%(upload_date)s-%(title)s.%(ext)s'" \
	yta="yt -x -f bestaudio/best" \
	YT="youtube-viewer" \
	ref="shortcuts >/dev/null; source ~/.config/shortcutrc" \
	upc="sudo pacman -Syu; pkill -RTMIN+8 i3blocks" \
	lsp="pacman -Qett --color=always | less" \
	ffmpeg="ffmpeg -hide_banner"

# My custom Functions and my own alias list

function taskProject(){
	echo "Please enter a task number \n followed by a project name."
	task $1 modify project:$2
}

alias ls=lsd
alias ll="ls -l -A"
alias cat="bat"
alias ta="task add $1"
alias report="task burndown.daily"
alias t="task list"
alias h="cd $HOME && taskell"
alias tpro=taskproject
alias tt="task $1 modify +$2"
alias scim=sc-im
alias jn="jupyter notebook"
alias bib="nvim $HOME/Documents/bib/uni.bib"
alias roth="roth | grep The"
alias py=bpython
alias python=bpython
alias ga="git add"
alias gs="git status"
alias gc="git commit"
alias gp="git push"

# end my custom alias's and functions

command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d" # Use neovim for vim if present.

vf() { cd $HOME/VimWiki && fzf --preview='bat --theme="Solarized (dark)" --style=numbers --color=always {} | head -500' | xargs -r -I % $EDITOR % ;}
vff() { fzf --multi --preview='bat --theme="Solarized (dark)" --style=numbers --color=always {} | head -500' --marker="~" | xargs -r -I % $EDITOR % ;}

