#!/usr/bin/env sh

alias ka="killall" \
	mkd="mkdir -pv" \
	mpv="mpv --input-ipc-server=/tmp/mpvsoc$(date +%s)" \
	calcurse="calcurse -D ~/.config/calcurse" \
	magit="nvim -c MagitOnly" \
	p="sudo pacman" \
	SS="sudo systemctl" \
	f="$FILE" \
	g="git" \
	trem="transmission-remote" \
	e="$EDITOR" \
	v="$EDITOR -p" \
	x="sxiv -ft *" \
	sdn="sudo shutdown -h now" \
	gua="git remote | xargs -L1 git push --all" \
	#ls="ls -hNA --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff -y -i -w -B --color" \
	ccat="highlight --out-format=ansi" \
	yt="youtube-dl --add-metadata -i -o '%(upload_date)s-%(title)s.%(ext)s'" \
	yta="yt -x -f bestaudio/best" \
	YT="youtube-viewer" \
	ref="shortcuts >/dev/null; source ~/.config/shortcutrc" \
	upc="sudo pacman -Syu; pkill -RTMIN+8 i3blocks" \
	lsp="pacman -Qett --color=always | less" \
	ffmpeg="ffmpeg -hide_banner"

# General aliasing
alias bib="nvim $HOME/Research/bib/mega.bib" \
	cat="bat" \
	ga="git add" \
	gc="git commit" \
	gp="git push" \
	gs="git status" \
	grep=rg \
	h="cd $HOME && taskell" \
	ls=lsd \
	ll="ls -l -A" \
	py=bpython \
	python=bpython \
	scim=sc-im \
	vifm="vu"

# My task warrior scripting
alias t="task list"

command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d" # Use neovim for vim if present.

vf() { cd $HOME/VimWiki && fzf --preview='bat --theme="Solarized (dark)" --style=numbers --color=always {} | head -500' | xargs -r -I % $EDITOR % ;}
vff() { fzf --multi --preview='bat --theme="Solarized (dark)" --style=numbers --color=always {} | head -500' --marker="~" | xargs -r -I % $EDITOR % ;}

